Repository GESkunkworks/gossamer3, pull requests merged in 2020-10, with the labels that each got.

#38 add documentation for linux pass keystore
  README.md
Labels: documentation

#37 clarify the message at the end of configure command
  cmd/gossamer3/commands/configure.go
Labels: bug

#36 adding region support
  README.md
  cmd/gossamer3/commands/bulk_login.go
  cmd/gossamer3/commands/console.go
  cmd/gossamer3/commands/exec.go
  cmd/gossamer3/commands/login.go
  cmd/gossamer3/commands/script.go
  pkg/cfg/rolecfg.go
Labels: enhancement

#42 session duration per role
  README.md
  cmd/gossamer3/commands/bulk_login.go
  cmd/gossamer3/commands/login.go
  pkg/cfg/rolecfg.go
Labels: enhancement

#46 adding password argument
  cmd/gossamer3/commands/login.go
  cmd/gossamer3/main.go
  pkg/flags/flags.go
Labels: enhancement

#48 track login attempts
  pkg/provider/pingfed/pingfed.go
Labels: enhancement

#49 enable mapping a default region to an account
  README.md
  cmd/gossamer3/commands/bulk_login.go
  cmd/gossamer3/commands/console.go
  cmd/gossamer3/commands/exec.go
  cmd/gossamer3/commands/login.go
  cmd/gossamer3/commands/script.go
  gossamer3_test.go
  pkg/cfg/rolecfg.go
Labels: enhancement

#51 pass ping error messages through to user
  pkg/provider/pingfed/pingfed.go
Labels: enhancement

#52 expand any home paths in the AWS_SHARED_CREDENTIALS_FILE env var
  pkg/awsconfig/awsconfig.go
Labels: bug

#53 handle password expiration errors
  pkg/provider/pingfed/example/password-expired.html
  pkg/provider/pingfed/pingfed.go
  pkg/provider/pingfed/pingfed_test.go
Labels: bug

#55 set user agent header to gossamer3
  cmd/gossamer3/commands/bulk_login.go
  cmd/gossamer3/commands/console.go
  cmd/gossamer3/commands/exec.go
  cmd/gossamer3/commands/login.go
  cmd/gossamer3/main.go
  pkg/awsconfig/awsconfig.go
  pkg/cfg/cfg.go
  pkg/provider/http.go
Labels: enhancement
